### ISSUE TITLE
[ERROR] Memory leak?

### ISSUE THREAD

**Issue by jameshackerbond** [arcadiadevs/playerservers-everything#26]
If you leave your hub server running for a long time it will cause this issue to happen, I first used paper now pufferfish. I can confirm its the same issue on papermc.

Here is the error log:
[00:51:39 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Pufferfish-58 (MC: 1.19.3) ---
[00:51:39 ERROR]: The server has not responded for 25 seconds! Creating thread dump
[00:51:39 ERROR]: ------------------------------
[00:51:39 ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[00:51:39 ERROR]: Ticking entity: minecraft:player, entity class: net.minecraft.server.level.EntityPlayer
[00:51:39 ERROR]: Entity status: removed: false, valid: true, alive: true, is passenger: false
[00:51:39 ERROR]: Entity UUID: 00000000-0000-0000-0009-01fb94aaeb31
[00:51:39 ERROR]: Position: world: 'world' at location (56.1094, 63.5, 11.713721)
[00:51:39 ERROR]: Velocity: (0.016782100938357105, 0.16477328182606651, 0.08885603622713299) (in blocks per tick)
[00:51:39 ERROR]: Entity AABB: AABB[55.80939998807907, 63.5, 11.41372098807907] -> [56.40940001192093, 65.29999995231628, 12.013721011920929]
[00:51:39 ERROR]: Total packets processed on the main thread for all players: 32285
[00:51:39 ERROR]: ------------------------------
[00:51:39 ERROR]: Current Thread: Server thread
[00:51:39 ERROR]:       PID: 34 | Suspended: false | Native: false | State: WAITING
[00:51:39 ERROR]:       Stack:
[00:51:39 ERROR]:               java.base@19.0.1/jdk.internal.misc.Unsafe.park(Native Method)
[00:51:39 ERROR]:               java.base@19.0.1/java.util.concurrent.locks.LockSupport.park(LockSupport.java:221)
[00:51:39 ERROR]:               java.base@19.0.1/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1864)
[00:51:39 ERROR]:               java.base@19.0.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3744)
[00:51:39 ERROR]:               java.base@19.0.1/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3689)
[00:51:39 ERROR]:               java.base@19.0.1/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1898)
[00:51:39 ERROR]:               java.base@19.0.1/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2072)
[00:51:39 ERROR]:               PSHubCore.jar//os.arcadiadevs.playerservers.hubcore.models.Server.getInfo(Server.java:121)
[00:51:39 ERROR]:               PSHubCore.jar//os.arcadiadevs.playerservers.hubcore.guis.SelectorGui.lambda$openGui$2(SelectorGui.java:49)
[00:51:39 ERROR]:               PSHubCore.jar//os.arcadiadevs.playerservers.hubcore.guis.SelectorGui$$Lambda$7271/0x000000080266cf40.apply(Unknown Source)
[00:51:39 ERROR]:               java.base@19.0.1/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[00:51:39 ERROR]:               java.base@19.0.1/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[00:51:39 ERROR]:               java.base@19.0.1/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[00:51:39 ERROR]:               java.base@19.0.1/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
[00:51:39 ERROR]:               java.base@19.0.1/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[00:51:39 ERROR]:               java.base@19.0.1/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[00:51:39 ERROR]:               java.base@19.0.1/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
[00:51:39 ERROR]:               java.base@19.0.1/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[00:51:39 ERROR]:               java.base@19.0.1/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:693)
[00:51:39 ERROR]:               PSHubCore.jar//os.arcadiadevs.playerservers.hubcore.guis.SelectorGui.lambda$openGui$10(SelectorGui.java:56)
[00:51:39 ERROR]:               PSHubCore.jar//os.arcadiadevs.playerservers.hubcore.guis.SelectorGui$$Lambda$7268/0x000000080266c440.accept(Unknown Source)
[00:51:39 ERROR]:               java.base@19.0.1/java.util.ArrayList.forEach(ArrayList.java:1511)
[00:51:39 ERROR]:               PSHubCore.jar//os.arcadiadevs.playerservers.hubcore.guis.SelectorGui.openGui(SelectorGui.java:30)
[00:51:39 ERROR]:               PSHubCore.jar//os.arcadiadevs.playerservers.hubcore.events.ClickEvent.onClick(ClickEvent.java:46)
[00:51:39 ERROR]:               com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor16.execute(Unknown Source)
[00:51:39 ERROR]:               org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[00:51:39 ERROR]:               co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[00:51:39 ERROR]:               org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[00:51:39 ERROR]:               org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:674)
[00:51:39 ERROR]:               org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:546)
[00:51:39 ERROR]:               org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:503)
[00:51:39 ERROR]:               org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:498)
[00:51:39 ERROR]:               org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:493)
[00:51:39 ERROR]:               org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:489)
[00:51:39 ERROR]:               net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItem(ServerGamePacketListenerImpl.java:2018)
[00:51:39 ERROR]:               net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:32)
[00:51:39 ERROR]:               net.minecraft.network.protocol.game.ServerboundUseItemPacket.a(ServerboundUseItemPacket.java:8)
[00:51:39 ERROR]:               net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51)
[00:51:39 ERROR]:               net.minecraft.network.protocol.PlayerConnectionUtils$$Lambda$7101/0x000000080258b658.run(Unknown Source)
[00:51:39 ERROR]:               net.minecraft.server.TickTask.run(TickTask.java:18)
[00:51:39 ERROR]:               net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153)
[00:51:39 ERROR]:               net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[00:51:39 ERROR]:               net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1343)
[00:51:39 ERROR]:               net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[00:51:39 ERROR]:               net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126)
[00:51:39 ERROR]:               net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1320)
[00:51:39 ERROR]:               net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1313)
[00:51:39 ERROR]:               net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114)
[00:51:39 ERROR]:               net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1447)
[00:51:39 ERROR]:               net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175)
[00:51:39 ERROR]:               net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[00:51:39 ERROR]:               net.minecraft.server.MinecraftServer$$Lambda$4411/0x00000008018c53d0.run(Unknown Source)
[00:51:39 ERROR]:               java.base@19.0.1/java.lang.Thread.run(Thread.java:1589)
[00:51:39 ERROR]: ------------------------------
[00:51:39 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[00:51:39 ERROR]: ------------------------------
[00:51:39 ERROR]: Could not pass event PlayerInteractEvent to PSHubCore v3-dev
java.lang.NullPointerException: null

**Comment by simplylate** [comment]
+1 Also experiencing the same issues.

**Comment by OpenSource03** [comment]
After how much time?

**Comment by jameshackerbond** [comment]
prob over an hour I think and the players that join is over 12 per 5 minute

**Comment by jameshackerbond** [comment]
Also with the issue about players getting disconnected and the OOM killer it is just GeyserMC acting up which is now fixed and the OOM killer was because my vps cgroup was 2 not 1.

**Comment by jameshackerbond** [comment]
This only effects the compass. The emerald and anything else just lag.

**Comment by jameshackerbond** [comment]
Issue no longer happens often

**Comment by OpenSource03** [comment]
The issue is still happening for other users. Reopening the issue until we have a fix.

**Comment by simplylate** [comment]
do you have an eta?

**Comment by OpenSource03** [comment]
Fixed in https://github.com/arcadiadevs/hubcore/actions/runs/4188391966

Update config:
https://github.com/arcadiadevs/hubcore/commit/12d928b4c2e6fb171f81fed8582ae971c6dc1b19#diff-58cdd3d308ccba6c594e040ff9c065bb11eeb6e30f35ba87694ea45d5ae6096c

First try with cache disabled. If it doesn't work, enable it and the lag will be gone.
